#!/bin/sh

clean() {
  (
    set -e
    cd $1
    find . -name \*.elc -exec rm {} \;
    find . -name .yas-compiled-snippets.el -exec rm {} \;
  ) &
}

rm -f ~/*.elc
rm -f *.elc
clean lisp
clean site-lisp
clean snippets
clean themes

