#!/bin/sh

clean() {
  (
    cd $1
    find . -name \*.elc -exec rm {} \;
    find . -name .yas-compiled-snippets.el -exec rm {} \;
  ) &
}

rm -f ~/*.elc
rm -f *.elc
clean lib
clean lisp
clean site-lisp
clean override
clean snippets
clean themes

