#!/bin/sh

arg=$1

set -e

get_emacs() {
    set -e
    mkdir -p ~/.opt
    cd ~/.opt
    if [ -d emacs ]; then
      cd emacs
      git pull
      make
      make info
    else
      git clone -b emacs-24 git://git.sv.gnu.org/emacs.git emacs
      cd emacs
      ./autogen.sh
      ./configure \
        --with-x-toolkit=lucid \
        --with-file-notification=inotify \
        --without-pop \
        --enable-link-time-optimization \
        --without-toolkit-scroll-bars
      make bootstrap
      make info
    fi
}

# Clone or update a git repository
getGit() {
    repo="${REPOS}/${name}"
    if [ -d "$repo" ]; then
        (
            cd ${repo}
            git pull
        )
    else
        git clone "$url" "${repo}"
    fi
    cd ${repo}
}

# Clone or update a bzr repository
getBzr() {
    repo="${REPOS}/${name}"
    if [ -d "$repo" ]; then
        (
            cd ${repo}
            bzr update
        )
    else
        bzr checkout "$url" "${repo}"
    fi
    cd ${repo}
}



case $arg in
    emacs)
        get_emacs
        ;;
    all)
        get_emacs
        ;;
    *)
        echo "usage $0 ..."
        ;;
esac
