#!/bin/bash
#
# Reset vendor/ to the state of the last commit.
#
#

set -e


git clean -fd site-lisp/
git checkout -- site-lisp/

git clean -fd override/
git checkout -- override/

git clean -fd lib/
git checkout -- lib/
